### ISSUE TITLE
panic_fmt with core::fmt::Arguments leads to big binary size 

### ISSUE THREAD

**Issue by fckt** [paritytech/pwasm-std#56]
In https://github.com/paritytech/pwasm-std/blob/master/src/panic.rs

Even if `_fmt: ::core::fmt::Arguments` is not used the trait impls (like Display) being made included into the final binary.
```rust
#[no_mangle]
#[lang = "panic_fmt"]
pub extern fn panic_impl(_fmt: ::core::fmt::Arguments, file_line_col: &(&'static str, u32, u32)) -> ! {
// ...
}
```

The current solution is just not use any arguments in panic_fmt
```rust
#[no_mangle]
#[lang = "panic_fmt"]
pub extern fn panic_impl() -> ! {
// ...
}
```

**Comment by Pzixel** [comment]
Close this?

**Comment by fckt** [comment]
@Pzixel yeah, thanks for pointing out
